### ISSUE TITLE
Catch the *tmp* [[sc]] error and add a description

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#107]
Apologies for the lack of information, I don't have much time to investigate this. I've worked around this error quite a few times, but I've never documented the solution to it, and have since forgotten the solution. To prevent this in the future, the next time someone works around this (including myself), they should document the solution. Additionally, we should find where the error occurs and catch it with a better description. I vaguely remember this having something to do with the weather database.

![image](https://user-images.githubusercontent.com/16931318/27671159-b76babc8-5c46-11e7-9dcc-914dbded18be.png)

The data in [this project](https://drive.google.com/drive/folders/0B-FsKC_ClM7WbURpOVFNVjlheFE) reproduces this error for me. Specifically, site 1 causes it (shown above). Note that you may not be able to run this directly, as it uses the CO2 branches.

Also note that the error itself may be coming from SOILWAT2.

**Comment by dschlaep** [comment]
The error message seems to be pretty self-explanatory to me "data missing for 1st layer; -> no data to impute: simulation will fail". Indeed, the SOILWAT2 execution does fail and the function 'do_OneSite' should 'prematurely' end in such cases. The behavior is intended.

My question is why does the appear to continue (and run into a [[sc]] error) even though `tasks$create <- 0L` as a consequence of the missing soil data. The code sets all elements of `tasks$execute` to -1L if `tasks$create <= 0L` and thus the SOILWAT2 simulation should not be executed and (the non-existing output) not aggregated.

The first [[sc]] statement that I can find after the code printed 'Start of SOILWAT2 execution for P_id...', is for the aggregation 'input_FractionVegetationComposition'.

I realized that the logic at the very beginning of the 'aggregate SOILWAT2 output' code section didn't do anything. Indeed, the statement `tasks$aggregate[sc] <- -1L` was mistakenly removed by a previous commit. I re-inserted this and no aggregation should no take place. Please see commit 2d1dcd85284dab7bedb9f39d52bf7aa588a3e781. Does this solve this issue?

**Comment by Zachary-Kramer** [comment]
I didn't know this error was linked to the "no data to impute" message, so yes it's just a matter of not executing the simulation.

My new_CO2 branch never got the `tasks$aggregate[sc] <- -1L` removed, so this is not the fix for me. The only functional difference I see for this statement is that the master branch has `is_SOILTEMP_INSTABLE`, whereas mine does not.

After merging master into new_CO2, this error no longer occurs.

Good work

**Comment by Zachary-Kramer** [comment]
After I resolved merge conflicts, rSFSW2 was actually targeting master's original Simulation_Run.R, which is when this bug went away for me. After properly targeting the merged Simulation_Run.R, this error came back. I have since pinpointed the section of code this occurs in for me. It's a fault of my code, so I'm re-opening this issue and assigning it to new_CO2.

**Comment by Zachary-Kramer** [comment]
Seems solved with https://github.com/Burke-Lauenroth-Lab/rSFSW2/commit/62c3e4f6f7958fc2ae5348a6e790df564c7d7ae5 due to replacing the culprit code
