### ISSUE TITLE
CO2 plots have repeated multipliers

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#109]
The time series 1969-2010 with scenarios at delta 50 and delta 90 have identical multipliers for years 2060 and 2061 across all test run sites.

More information to come with investigation.

**Comment by CaitlinA** [comment]
I am uncertain if this is true. 

Looking at the outputs from the test Validation project, while years are repeated between two time periods/scenarios, the multipliers themselves are continuous. You can check this by observing  the @CO2Effects output.

 I attached time series plots below which reflect a complete pull of all sites, years, and scenarios (aka no subsetting out years so there is no overlap. I think I did this incorrectly before in previous iterations of plots).

![biomulti](https://user-images.githubusercontent.com/13442815/28082581-b645f998-6627-11e7-8683-08b2acb1b0f4.png)
![wuemulti](https://user-images.githubusercontent.com/13442815/28082585-b86fb3f8-6627-11e7-84ee-3efbc2a14a0f.png)

**Comment by Zachary-Kramer** [comment]
Yes, it appears that the output is continuous, at least in my most recent runs, which is good news because if the spin up years were causing issues it would be difficult to solve. I'm unsure if this is a recent fix or if plotting was the issue, but either way this issue seems solved.
