### ISSUE TITLE
Delta years stored in sim_scens variable are all NA

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#118]
The delta years are generated by parsing the delta string years, however the parsing does not cut away enough characters. 

For instance, the string "d50yrs" turns into "d50y". When "d50y" is converted to an integer, it becomes NA. Cut 1 more letter from the start (2 total due to 1-based index) and 1 more from the end (3 total).

**Comment by dschlaep** [comment]
Yep, sorry. I had fixed it already with commit 49603e1cd1eb9ff48e534610062259fbc2f98b91, but inadvertently on a development branch 'fix_adding_climscen_consequences' instead of master. Thanks.
