### ISSUE TITLE
Why is weekly output not used?

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#206]
I just finished implementing daily and weekly output for CO2, but realized that weekly output was not showing up. In fact, none of the outputs have weekly data, which is because in Simulation_Run.R the time periods are set to daily, monthly, and yearly:

![image](https://user-images.githubusercontent.com/16931318/31239095-4641cc30-a9fc-11e7-9d63-dc37b13fb0df.png)

![image](https://user-images.githubusercontent.com/16931318/31238573-a8cfa400-a9fa-11e7-8c17-2b9eee997b02.png)

Adding ` weeky = 1,` generates weekly output.

Is there a reason for it being disabled?

**Comment by dschlaep** [comment]
`rSFSW2` does not use weekly output. Hence, `rSFSW2` disables the generation of weekly output.

This is not to say that other uses of `SOILWAT2` and `rSOILWAT2` may need weekly output. Thus, `SOILWAT2` and `rSOILWAT2` need the capability to produce weekly output on demand.

**Comment by Zachary-Kramer** [comment]
Makes sense. I tested weekly output through rSFSW2 just in case.
