### ISSUE TITLE
Input of carbon data: by scenario lookup

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/rSFSW2#217]
- Design and experimental input files, i.e., `SWRuns_InputData_ExperimentalDesign_v06.csv` and `SWRuns_InputData_TreatmentDesign_v14.csv`, need to gain each a new column. Let's say `LookupCarbonScenario`.
- This column will operate similarly as for example `LookupTranspRegionsFromTable`
- String values of `LookupCarbonScenario` will subset a column of a spreadsheet located in a new folder `1_Data_SWInput/treatments/LookupCarbonScenario/` which contains a spreadsheet where rows = calendar years and columns = scenarios. For a specific run, rSFSFW2 picks a specific column, subsets rows to simulation years and sends this numeric vector to rSOILWAT2.

**Comment by Zachary-Kramer** [comment]
What's wrong with the current CO2Scenario column in experimental/treatment? Should it just be renamed to LookupCarbonScenario?

**Comment by dschlaep** [comment]
Yes, rename the column `CO2_Scenario` to `LookupCarbonScenario` and implement functionality as described above.

> It's currently being used to find the scenario stored in SOILWAT2's carbon.in

--> This doesn't work and cannot work as stated. `rSFSW2` does not have access to the `SOILWAT2`-run-time version of `carbon.in`.

**Comment by dschlaep** [comment]
`LookupCarbonScenario.csv` needs a column `Year` to clearly indicate which calendar year a row is representing

**Comment by Zachary-Kramer** [comment]
Okay, can do. What's wrong with just the rows representing the years? That's what was requested

**Comment by dschlaep** [comment]
Everything is set up code wise. The spreadsheet has a column 'Year' -- but you need to enter the correct year values. And update the other copies of this file.

**Comment by Zachary-Kramer** [comment]
rSFSW2 seems to work properly with your code and the new populated column
