### ISSUE TITLE
Get new_co2 pull request to pass

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#229]
Current reasons for failure:
```
testthat results ================================================================
OK: 2497 SKIPPED: 2 FAILED: 3
1. Failure: Test projects (@test_projects.R#33) 
2. Failure: Test projects (@test_projects.R#34) 
3. Failure: Test projects (@test_projects.R#37) 
```
Here are the respective unit tests:
```
#33
expect_false(any(tp[["res"]][, "has_problems"]), info = info_res)

#34
expect_null(tp[["report"]], info = info_report)

#37
# Print environmental variables if any problem occurred
expect_true(
  identical(all(tp[["res"]][, "has_run"]), TRUE) &&
  identical(any(tp[["res"]][, "has_problems"]), FALSE) &&
  is.null(tp[["report"]]),
  info = info_env)
```

So, all three failing just means that the run encountered problems. The problems are can be seen here [20171205-1421_Test_project_report.txt](https://github.com/Burke-Lauenroth-Lab/rSFSW2/files/1531259/20171205-1421_Test_project_report.txt), which are all aggregation issues.

One line that catches my eye is:
`reference and test database have a different design`

I believe this is because of the changes to the experimental design, so the headers are different. Thus, the reference DB will need to be updated...but we cannot update the DB until we know why the other aggregations are different.

The aggregations do show that the test's biomass is the same as the reference, so we know that CO2 effects are not impacting biomass. The multiplier for the transpiration equation is 1.0, so there should be no effects there either. Therefore, I believe this is some input issue.

Here are the test database output and the reference database.
[dbOutput.zip](https://github.com/Burke-Lauenroth-Lab/rSFSW2/files/1531302/dbOutput.zip)

**Comment by CaitlinA** [comment]
Hi Zach,

Just to clarify, you are testing against the reference database with all CO2 effects turn off?

@dschlaep Is it advised that we update the reference database?

**Comment by Zachary-Kramer** [comment]
Yes, in the experimental design I have disabled the effects. I then double-checked in SOILWAT2 that the function apply_biomassCO2effect has no effect in this situation. The WUE multiplier is also 1.0 so I am assuming that it also has no effect.

**Comment by dschlaep** [comment]
Input biomass values are the same; however, actual biomass values are not constant even if all multipliers are 1:
```
> runDataSC@CO2EFFECTS@Year
      Year GrassBiomass ShrubBiomass TreeBiomass ForbBiomass
 [1,] 1979     170.0586     366.5337           0           0
 [2,] 1980     169.9719     366.2766           0           0
 [3,] 1981     170.0586     366.5337           0           0
 [4,] 1982     170.0586     366.5337           0           0
 [5,] 1983     170.0586     366.5337           0           0
 [6,] 1984     169.9719     366.2766           0           0
 [7,] 1985     170.0586     366.5337           0           0
```

--> `SOILWAT2` error when accounting for leap years?

**Comment by dschlaep** [comment]
Not an error. Average yearly biomass is the average of the daily values. Daily values are interpolated from monthly values. We cannot expect that we don't change the mean if we add one day (i.e., it is most unlikely that the biomass of that day corresponds to the mean). For instance, `mean(1:10) != mean(c(x, 1:10)` for all `x != 5.5`.

These are minimal deviations from what we had in the past, e.g., `Transpiration_Total_mm_mean: Mean absolute difference: 0.071 [mm/year]`. I suggest that we accept those differences.
