### ISSUE TITLE
STATSGO Data: 'breaks' are not unique

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#89]
When STATSGO data is extracted/ran, I often get the error: "Error in cut.default(dat, n_cols): 'breaks' are not unique". This occurs during the map_input_variables section. From a bit of searching, it seems this error occurs when data is too similar between columns. A potential solution is to modify the cut function call to force unique breaks, but I'm unsure if that will have any unintended consequences. I will experiment with this a bit, but wanted to open an issue to get other suggestions, and to see if anyone else has encountered this error. I've attached my data.

[STATSGO data.zip](https://github.com/Burke-Lauenroth-Lab/rSFSW2/files/977673/STATSGO.data.zip)

**Comment by dschlaep** [comment]
Plotting maps of the input variables is only there to check the input variables. You can turn this off for your runs or please fix the code of map_input_variables to force unique breaks. Stuff inside this function will not affect the simulation. Thanks

**Comment by dschlaep** [comment]
I had to revert the closing commit 149e5d3 and submitted a fix that doesn't break the color-legend. @Zachary-Kramer: 



Does this work for you?

btw, using na.exclude instead of a built-in argument na.rm = TRUE makes code slow:

 ```
  NAs_percents data_lengths ratio of call time for min(na.exlcude(x)) vs. min(x, na.rm = TRUE)
1          0.00        0e+00          1.2
2          0.25        0e+00          1.2
3          0.50        0e+00          1.2
4          0.75        0e+00          1.2
5          1.00        0e+00          1.2
6          0.00        1e+01         12.0
7          0.25        1e+01         18.7
8          0.50        1e+01         19.4
9          0.75        1e+01         20.4
10         1.00        1e+01          1.3
11         0.00        1e+02          8.2
12         0.25        1e+02         17.0
13         0.50        1e+02         19.0
14         0.75        1e+02         20.4
15         1.00        1e+02          1.4
16         0.00        1e+04          2.4
17         0.25        1e+04          6.3
18         0.50        1e+04          8.2
19         0.75        1e+04         10.6
20         1.00        1e+04          4.5
21         0.00        1e+06          2.8
22         0.25        1e+06         13.5
23         0.50        1e+06         16.8
24         0.75        1e+06         20.6
25         1.00        1e+06         23.8
```
