### ISSUE TITLE
SSURGO sites commonly fail the yearlyWaterBalanceFluxes aggregation

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#91]
This is one of a few aggregations that most SSURGO sites fail. 

When R executes `swc.flux <- tapply(swcdyflux, temp1[index.usedyPlusOne, 1], sum)` in Simulation_Run.R, the following error is produced: 'arguments must have same length'.

I believe the culprit is the top layer. The aggregation fails when length(topL) < 1. It often succeeds when it is > 1. As an example, SSURGO often has `topL = c(1)` and STATSGO has values like `topL = c(1,2,3)`. 

Forcing the aggregation into thinking the length of topL is > 1 often works. For instance, setting this if statement to TRUE will often succeed (but not always):

```
          if (length(topL) > 1) {
            swcdyflux <- apply(temp1[index.usedyPlusOne, 2+ld], 1, sum) - apply(temp1[index.usedyPlusOne-1, 2+ld], 1, sum)
          } else {
            swcdyflux <- temp1[index.usedyPlusOne, 2+ld] - temp1[index.usedyPlusOne-1, 2+ld]
          }

          swc.flux <- tapply(swcdyflux, temp1[index.usedyPlusOne, 1], sum) # SSURGO fails

```

```
          if (TRUE) {
            swcdyflux <- apply(temp1[index.usedyPlusOne, 2+ld], 1, sum) - apply(temp1[index.usedyPlusOne-1, 2+ld], 1, sum)
          } else {
            swcdyflux <- temp1[index.usedyPlusOne, 2+ld] - temp1[index.usedyPlusOne-1, 2+ld]
          }

          swc.flux <- tapply(swcdyflux, temp1[index.usedyPlusOne, 1], sum) # SSURGO succeeds

```

I don't know what to think of this, besides that the aggregation perhaps is not prepared to work with SSURGO's large layer widths. In the meantime, I am leaving this aggregation disabled on SSURGO and am open to suggestions on why this might be happening.

Here's some info on a site that failed:

**Layer info:**
Soildepth: 33cm
Layer 1: 5cm
Layer 2: 33cm

**Texture info:**
Matricd_L1: 1.35
GravelContent_L1: 0.1625
Sand_L1: 0.669
Clay_L1: 0.1
Matricd_L2: 1.33
GravelContent_L2: 0.095
Sand_L2: 0.354
Clay_L2: 0.31

**Comment by dschlaep** [comment]
@Zachary-Kramer could you please send me a RData file with the necessary objects (e.g., as generated by save(…))? I cannot reproduce this myself and not having the objects makes looking into this issue harder. Thanks.

**Comment by Zachary-Kramer** [comment]
Here's the input/output for a failed site.

[Uploading 001_DefaultSettings_AZ_53131.zip…]()

Thank you for looking into this

**Comment by dschlaep** [comment]
The link doesn’t lead to a file — instead it references only issue #91. Can you please check?

**Comment by Zachary-Kramer** [comment]
It looks like I didnt let it finish uploading before I commented. I'll repost it once I have access to my laptop. This aggregation issue may not matter anymore because I will be interpolating my layers to match STATSGO depths

**Comment by Zachary-Kramer** [comment]
Sorry for the delay, I was in the middle of moving

[001_DefaultSettings_AZ_53131.zip](https://github.com/Burke-Lauenroth-Lab/rSFSW2/files/1049292/001_DefaultSettings_AZ_53131.zip)

**Comment by dschlaep** [comment]
The attached data is insufficient for decent debugging. The attached data contain the RData input and output files from a run from rSOILWAT2. What would be required here are all the necessary R objects to execute the code for the aggregation in question.

I know this is currently rather cumbersome, but it will be easier once all the aggregations have been converted to functions (see issue #62). I suggest that a somewhat convenient workaround is to place a stop() at the end of the targeted aggregation code and run the simulation with opt_verbosity[["debug.dump.objects"]] set to TRUE.

**Comment by dschlaep** [comment]
I double checked the indicated lines of code and they produce good output in my made-up examples. Maybe the variables 'ld' and 'topL' get in your runs somehow out of sync?

**Comment by dschlaep** [comment]
Using
- commit 5d4e34cb5527c40ea80836cf2c58da9129b4f9f1
- opt_agg: aon_toplayer_cm = 20
- req_out: overall_out: yearlyWaterBalanceFluxes, 1

I can replicate this error message by setting soil layers (and soil depth) for test project 4 to:
- 50, 80, 100, 120, 150 cm
- 15, 50 cm
- 10, 50 cm
- 5, 50 cm
- 5, 21 cm

I get no error for:
- 5, 20, 50 cm
- 5, 20 cm
- 5, 15 cm
- 50 cm
- 5 cm


Error message:
> [1] "Aggregation of yearlyWaterBalanceFluxes"
> [1] "rSFSW2's 'do_OneSite': ended prematurely for simulation = 1"
> Error in tapply(swcdyflux, temp1[index.usedyPlusOne, 1], sum) : 
>   arguments must have same length

==> It appears that this error is expressed only if
- number of soil layers > 1, and
- number of soil layers (with depths <= aon_toplayer_cm) <= 1

==> commit 69c3266c0c4978697145503ec39db5e894e202b8 fixes this issue and works for all above listed soil layer specifications
