### ISSUE TITLE
dailyNRCS_SoilMoistureTemperatureRegimes aggregation fails when the first layer is deeper than 10cm

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSFSW2#92]
A warning message is given:
```
"004_DefaultSettings_NM_03074 interpolated soil layers for NRCS soil regimes because of insufficient soil layers: required would be {10, 30, 50, 70} and available are {13, 48, 152}"
```
Then a few different errors, depending on the site:
```
Error in if (MCS_COND3 && (!MCS_COND4 && MCS_COND5 && MCS_COND6 || (MCS_COND4 ||  : 
  missing value where TRUE/FALSE needed

Error in if (MAST >= 22) { : missing value where TRUE/FALSE needed

...
```
This is not hindering my SSURGO progress, as I already limit the first layer to 15 and can instead limit it to 10, but it seems that this aggregation should be able to handle my layer depths. Is rSFSW2 not intended to support first layers deeper than 10cm? I limited the first layer to 15 because there's a comment stating that the depth_max_bs_evap has a default value of 15.

I can provide data as needed, though this seems fairly reproduce-able by just making the first layer > 10.

**Comment by dschlaep** [comment]
@Zachary-Kramer could you please send me a RData file with the necessary objects (e.g., as generated by save(…))? I cannot reproduce this myself and not having the objects makes looking into this issue harder. Thanks.

**Comment by Zachary-Kramer** [comment]
Here's the data for a failed site.

[004_DefaultSettings_NM_03074.zip](https://github.com/Burke-Lauenroth-Lab/rSFSW2/files/1030047/004_DefaultSettings_NM_03074.zip)

For me it seems to be replicable when making any site's first layer deeper than 10cm, though my tests haven't been thorough.

**Comment by dschlaep** [comment]
The attached data is insufficient for decent debugging. The attached data contain the RData input and output files from a run from rSOILWAT2. What would be required here are all the necessary R objects to execute the code for the aggregation 'dailyNRCS_SoilMoistureTemperatureRegimes'.

I know this is currently rather cumbersome, but it will be easier once all the aggregations have been converted to functions (see issue #62). I suggest that a somewhat convenient workaround is to place a stop() at the end of the targeted aggregation code and run the simulation with opt_verbosity[["debug.dump.objects"]] set to TRUE.

Also, it appears that the simulation inputs were created with an outdated version of the wrapper Rsoilwat31? -- That would be a version from before it was converted to a package rSFSW2.

**Comment by dschlaep** [comment]
Using
- commit 69c3266c0c4978697145503ec39db5e894e202b8
- req_out: overall_out: dailyNRCS_SoilMoistureTemperatureRegimes_Intermediates, 1

Message from 'dailyNRCS_SoilMoistureTemperatureRegimes_Intermediates':
> "interpolated soil layers for NRCS soil regimes because of insufficient soil layers: required would be {10, 30, 50}"

I can replicate this error message by setting soil layers (and soil depth) for test project 4 to:
- 50, 80, 100, 120, 150 cm
- 15, 50 cm
- 15, 30, 50 cm
- 15, 30 cm
- 50 cm
- 30 cm
- 15 cm

I get no error for:
- 10, 50 cm
- 5, 50 cm
- 5, 30 cm
- 5, 30, 50 cm
- 10 cm
- 5 cm

Error message:
> [1] "Aggregation of dailyNRCS_SoilMoistureTemperatureRegimes"
> [1] "rSFSW2's 'do_OneSite': ended prematurely for simulation = 1"
> Error : length(w) == 2L is not TRUE

==> It appears that this error from function 'add_layer_to_soil' is expressed only if there is no soil layer at depth less or equal to the first layer depth required by NRCS soil regimes

==> commit 878081acb14c1a54bdabdef6f5097e72040d0336 fixes this issue and works for all above listed soil layer specifications
